export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
}

export enum AppView {
  TRIAGE,
  DASHBOARD,
}

export enum Role {
  PATIENT = 'Patient',
  DOCTOR = 'Doctor',
  ADMIN = 'Admin',
}

// Corresponds to the 'profiles' table in Supabase
export interface Profile {
  id: string; // UUID from auth.users
  name: string;
  role: Role;
  details?: string; 
}

// Corresponds to the 'triage_sessions' table
export interface TriageSession {
  id: string; // UUID, generated by Postgres
  patient_id: string; // Foreign key to profiles
  created_at: string; // Timestamp
  summary: string;
  chat_history: ChatMessage[]; // JSONB
  doctor_notes: string | null;
}

// Corresponds to the 'appointments' table
export interface Appointment {
  id: string; // UUID
  patient_id: string;
  doctor_id: string;
  appointment_date: string;
  reason: string;
  status: 'Confirmed' | 'Pending' | 'Cancelled';
}